                                         Icecream

In [4]:
from icecream import ic
num1=12
num2=13

ic(num1)
ic(num2)

print(num2)


ic| num1: 12
ic| num2: 13


13


In [7]:
def plus_five(num):
    return num + 5

print(ic(plus_five(4)))
print(ic(plus_five(5)))

ic| plus_five(4): 9
ic| plus_five(5): 10


9
10


In [8]:
def plus_five(num):
    return num + 5

ic(plus_five(4))
ic(plus_five(5))

ic| plus_five(4): 9
ic| plus_five(5): 10


10

In [9]:
def hello(user:bool):
    if user:
        ic()
    else:
        ic()

hello(user=True)

ic| <ipython-input-9-2e6d23255589>:3 in hello() at 17:36:29.160


In [10]:
from datetime import datetime
from icecream import ic 
import time

def time_format():
    return f'{datetime.now()}|> '

ic.configureOutput(prefix=time_format)

for _ in range(3):
    time.sleep(1)
    ic('Hello')

2021-03-22 23:09:02.021320|> 'Hello'
2021-03-22 23:09:03.084446|> 'Hello'
2021-03-22 23:09:04.106467|> 'Hello'


In [11]:
from icecream import ic 

def plus_five(num):
    return num + 5

ic.configureOutput(includeContext=True)
ic(plus_five(4))
ic(plus_five(5))

2021-03-22 23:11:04.422090|> <ipython-input-11-826dd3392d51>:7 in <module>
                             plus_five(4): 9
2021-03-22 23:11:04.474150|> <ipython-input-11-826dd3392d51>:8 in <module>
                             plus_five(5): 10


10

                                       Descriptors

In [4]:
class Mydescriptors(object):
    def __init__(self,initval=None):
        print("__init__ of MyDescriptors called  with initial value:",initval)
        self.__set__(set,initval)
        
    def __get__(self,instance, owner):
        print(instance,owner)
        print("Getting self.val:", self.val)
        
    def __set__(self,instance,value): 
        print("Setting Self.val to", value)
        self.val = value

class Model(object):
    temp=Mydescriptors(37)   # descriptor is attached the class definiation time
    
body=Model()

__init__ of MyDescriptors called  with initial value: 37
Setting Self.val to 37


                                     Enumerator

In [3]:
l1=[12,13,14,15,16]

for i,j in enumerate(l1):
    print(j,end=" ")
    print()
    print(i,end=" ")

12 
0 13 
1 14 
2 15 
3 16 
4 

#                                   Public, Private, Protected            

Public vs Private attributes
Based on accessibility, attributes can be categorized into 3 categories:

Public  
Protected  
Private    

|Name||Type||Description|
|----||----||-----------|
|name||public||The attribute is available both inside and outside class|
|_name||protected||should not be should outside class definition |
|__name	||private||inaccessible and invisible outside class definition|

In [3]:
class Insan():
    
    def __init__(self):
        self.__ghar = "I am private"
        self._gari = "I am protected"
        self.name = "I am public"

x = Insan()

x.name

'I am public'

In [4]:
x._gari

'I am protected'

In [5]:
x.__ghar

AttributeError: 'Insan' object has no attribute '__ghar'

Although the Insan class do have an attribute anmed __priv, however the error is saying Insan object has no attribute __priv. What better privacy can there be?

We can also set the values of public attributes.

In [6]:
x.name = 'hasan'

x.name

'hasan'

private attribute is not accessible outside the class but we can use them inside class definition as follows:

In [8]:
class Insan():
    
    def __init__(self):
        self.__ghar = "I am private"
        self._gari = "I am protected"
        self.name = "I am public"

    
    def get_ghar(self):
        return self.__ghar

a = Insan()
a.get_ghar()

'I am private'

# name mangling

Every attribute with double underscore will be changed to object._class__attribte

In [9]:
ali._Insan__ghar

'I am private'

Ways of accessing and setting attribute value

In [15]:
class Human:
 
    def __init__(self, name=None, dob=2000):
        self.__name = name # protected attribute
        self.__dob = dob   # Protected attribute
        
    def say_hello(self):
        if self.__name:
            print("hello, I am " + self.__name)
        else:
            print(", I am a person without a name")
            
    def set_name(self, name):
        self.__name = name
        
    def get_name(self):
        return self.__name    

    def set_dob(self, by):
        self.__dob = by
        
    def get_dob(self):
        return self.__dob    
    
    def __repr__(self):
        return "Human('" + self.__name + "', " +  str(self.__dob) +  ")"

    def __str__(self):
        return "Name: " + self.__name + ", born in Year: " +  str(self.__dob)


x = Human("akash", 1996)
y = Human("golu", 1995)
for fard in [x, y]:
    fard.say_hello()
    if fard.get_name() == "Sadr":
        fard.set_dob(1353)
    print("I was born in the year " + str(fard.get_dob()) + "!")

hello, I am akash
I was born in the year 1996!
hello, I am golu
I was born in the year 1995!


#                                   Class and Instance attributes

In [16]:
class student: 
    course = "Btech"

x = student()
y = student()

x.course

'Btech'

In [17]:
y.course

'Btech'

In [18]:
x.course = "Mtech"
y.course

'Btech'

In [19]:
student.course

'Btech'

In [21]:
student.course="Pg"
student.course

'Pg'

In [22]:
x.course

'Mtech'

In [23]:
y.course

'Pg'

Because the attribute was changed for class and instance x was created before this change so x still has old attribute value.

In [24]:
x.__dict__

{'course': 'Mtech'}

In [25]:
y.__dict__

{}

Because y itself does not have attribute course so it looked for the attribute value in class student and used that value for itself.

In [26]:
student.__dict__

mappingproxy({'__module__': '__main__',
              'course': 'Pg',
              '__dict__': <attribute '__dict__' of 'student' objects>,
              '__weakref__': <attribute '__weakref__' of 'student' objects>,
              '__doc__': None})

So class attributes and isntance attributes can have different values. We can find out attributes of class of an instance from the instance using following clode

In [27]:
x.__class__.__dict__

mappingproxy({'__module__': '__main__',
              'course': 'Pg',
              '__dict__': <attribute '__dict__' of 'student' objects>,
              '__weakref__': <attribute '__weakref__' of 'student' objects>,
              '__doc__': None})

In [28]:
class philosopher:

    Quotes = (
"""What cannot be imagined cannot even be talked about.""",
"""Philosophy is a battle against the bewitchment of our intelligence by means of language.,""",
"""The limits of my language means the limits of my world."""
)

    def __init__(self, name='Wittgenstein', dob=1889):
        self.name = name
        self.build_year = build_year

    # other methods as usual

In [29]:
for number, quote in enumerate(philosopher.Quotes):
    print(str(number+1) + ":\n" + quote)

1:
What cannot be imagined cannot even be talked about.
2:
Philosophy is a battle against the bewitchment of our intelligence by means of language.,
3:
The limits of my language means the limits of my world.


# Counting instances of a class

In [32]:
class Human: 

    counter = 0
    
    def __init__(self): 
        # every time a new instance is created the attribute 'counter' of 'Human' increases by 1
        type(self).counter += 1

    def __del__(self):
        # every time an instance of `Insan` is deleted, the attribute 'counter' of 'Human' decreases by 1
        type(self).counter -= 1


x = Human()
print("Population count is: : " + str(Human.counter))
y = Human()
print("Population count is: : " + str(Human.counter))
del x
print("Population count is: : " + str(Human.counter))
del y
print("Population count is: : " + str(Human.counter))

Population count is: : 1
Population count is: : 2
Population count is: : 1
Population count is: : 0


#                            static methods

The way to solve this problem is to put the decorate @staticmethod. By doing so, python will not put the instance implicitly as first input argument.

In [33]:
class Insan:
    __counter = 0
    
    def __init__(self):
        type(self).__counter += 1
        
    @staticmethod
    def PopulationCount():
        return Insan.__counter
        


print(Insan.PopulationCount())
ali = Insan()
print(ali.PopulationCount())
hasan = Insan()
print(hasan.PopulationCount())
print(Insan.PopulationCount())

0
1
2
2


##                          why to use them?

Static methods are used to group a utility function with a class.

In [35]:
class Dates:
    def __init__(self, date):
        self.date = date
        
    def getDate(self):
        return self.date

    @staticmethod
    def toDashDate(date):
        return date.replace("/", "-")

date = Dates("15-12-2016")
dateFromDB = "15/12/2016"
dateWithDash = Dates.toDashDate(dateFromDB)

since toDashDate works only for dates, it's logical to keep it inside the Dates class

Consider another example. Suppose we have a large number of examples which perform mathmatical functions such as ceil, multiply, exponent, devide on some input arguments. Then it would be logical to just group all such functions one one class such as math and use the functions as math.ceil(2.2) or math.exp(2.3) etc.

In [36]:
class math():

    @staticmethod
    def ceil(x):
        # perform ceil operation
        return

    @staticmethod
    def exp(x):
        # perform exponent operation
        return
    
    # more methods

                                          Classmethod

In [9]:
class Student:
    def __init__(self,name,marks):
        self.name=name
        self.marks=marks
        
    def got(self):
        print(self.name+" got "+self.marks)

name="akash"
marks="650"
marks1=str((int(marks)/700 )*100)
s1=Student(name,marks1)    
s1.got()

akash got 92.85714285714286


In [21]:
class Student1:
    def __init__(self,name,marks):
        self.name=name
        self.marks=marks
        
    def got(self):
        print(self.name+" got "+self.marks)
       
    @classmethod
    def get_percentage(cls,name,marks):
        return cls(name,str((int(marks)/700 )*100))

name="akash"
marks="680"
# s2=Student1(name,marks)
s2=Student1.get_percentage(name,marks)   
s2.got()

akash got 97.14285714285714


                                          Property

In [22]:
class Model:

    def __init__(self, temp):
        self.temp = temp

    @property
    def temp(self):
        # get temperature from the model through some process
        return self._temp

    @temp.setter
    def temp(self, x):
        if x>45:
            x = 45
        if x < 20:
            x = 20
        self._temp = x
        return
    
x = Model(39)
print(x.temp)

x.temp = x.temp*0.9
print(x.temp)

39
35.1


In [29]:
""" Problem , As you """
class Student:
    def __init__(self,name,grade):
        self.name=name
        self.grade=grade
        self.msg=self.name+" got grade "+self.grade
        
s1=Student("akash",'A')   
print("name: ", s1.name)
print("grade: ", s1.grade)
print(s1.msg)

print()
s1.grade="A+"
print("name: ", s1.name)
print("grade: ", s1.grade)
print(s1.msg)

name:  akash
grade:  A
akash got grade A

name:  akash
grade:  A+
akash got grade A


In [30]:
class Student:
    def __init__(self,name,grade):
        self.name=name
        self.grade=grade
        
    def msg(self):
        return self.name+" got grade "+self.grade
s1=Student('golu','A')
s1.grade="A+"
print("name: ", s1.name)
print("grade: ", s1.grade)
print(s1.msg())

name:  golu
grade:  A+
golu got grade A+


In [32]:
"""Property decorator allow us to use method as attribute"""
class Student:
    def __init__(self,name,grade):
        self.name=name
        self.grade=grade
    @property    
    def msg(self):
        return self.name+" got grade "+self.grade
s1=Student('golu','A')
s1.grade="A+"
print("name: ", s1.name)
print("grade: ", s1.grade)
print(s1.msg)


name:  golu
grade:  A+
golu got grade A+


In [34]:
class Student:
    def __init__(self,name,grade):
        self.name=name
        self.grade=grade
    @property    
    def msg(self):
        return self.name+" got grade "+self.grade
    @msg.setter
    def msg(self,msg):
        sent=msg.split(" ")
        print(sent)
        self.grade=sent[-1]
        self.name=sent[0]
    
s1=Student('golu','A')
s1.grade="A+"
s1.msg="akash got grade A++"
print("name: ", s1.name)
print("grade: ", s1.grade)
print(s1.msg)

['akash', 'got', 'grade', 'A++']
name:  akash
grade:  A++
akash got grade A++


In [47]:
class Student:
    def __init__(self,marks):
        self.__marks=marks    
    def percentage(self):
        return ((self.__marks*100//600))
    
    def setter(self,value):
        self.__marks=value
       
    def getter(self):
        return self.__marks
        
s1=Student(500)
s1.setter(550)
print(s1.getter())
print(s1.percentage())


550
91


In [54]:
class Student:
    def __init__(self,marks):
        self.__marks=marks    
    def percentage(self):
        return ((self.__marks*100//600))
    @property
    def marks(self):
        print("getting vale:",end=" ")
        return self.__marks
    @marks.setter        
    def marks(self,value):
        if value<0 or value>600:
            print("please check the value")
        else:
            print("setting vale:",value)
            self.__marks=value

        
s1=Student(500)
s1.marks=601
print(s1.marks)
print(s1.percentage())

please check the value
getting vale: 500
83


In [59]:
class Student3:
    def __init__(self,marks):
        self.__marks=marks    
    def percentage(self):
        return ((self.__marks*100//600))
    
    def setter(self,value):
        if value<0 or value>600:
            print("please check the value")
        else:
            print("setting vale:",value)
            self.__marks=value
       
    def getter(self):
        print("getting vale:",end=" ")
        return self.__marks
    
    marks=property(getter,setter)
        
s1=Student3(500)
s1.marks=400
print(s1.percentage())

setting vale: 400
66


                                         Decorator

In [35]:
def fun1(fun2):
    def lower():
        print('i am akash verma')
        fun2()
        print('i am pursuing master from nitk')
    return lower

def fun3(fun1):
    def lower():
        print('###########')
        fun1()
        print('$$$$$$$$$$$')
    return lower

@fun3
@fun1
def fun2():
    print('i am from gwalior')
    
fun2()    
    

###########
i am akash verma
i am from gwalior
i am pursuing master from nitk
$$$$$$$$$$$


# Type

In [48]:
class A:
    y=20


a=A()
b=A()
print(type(a))
print(type(b))
print(type(A))

<class '__main__.A'>
<class '__main__.A'>
<class 'type'>


In [49]:
# dynamic way to create a class
c=type("aksh",(A,),{})
print(c.y)
print(type(c))
print(type(c()))

20
<class 'type'>
<class '__main__.aksh'>


In [50]:
class Meta(type):
    pass
class askl(metaclass=Meta):
    pass
type(askl)

__main__.Meta

In [51]:
type(Meta)

type

In [57]:
class Metatwo(type):
    def __new__(self,*args,**kwargs):
        print("hello again")
    
    def __init__(self,*args,**kwargs):
        print("this")
        
class Python(metaclass=Metatwo):
    pass
    
# a=Python()


hello again


                                           Class 

In [31]:
class student:
    def __init__(self,name,rollno):
        self.name=name
        self.rollno=rollno

    def name(self,name):
        print('name of student',name)
        
st1=student('aksh',21) 
# st1.name('akash')

    

In [14]:
class student:
    def __init__(self,name,rollnum):
        self.name=name
        self.rollno=rollnum
        
    def info(self,name,rollnum):
        print(name)
        print(rollnum)
        

s1=student('akash',23)
s1.info('golu',23)
        

golu
23


In [55]:
help(property)

Help on class property in module builtins:

class property(object)
 |  property(fget=None, fset=None, fdel=None, doc=None)
 |  
 |  Property attribute.
 |  
 |    fget
 |      function to be used for getting an attribute value
 |    fset
 |      function to be used for setting an attribute value
 |    fdel
 |      function to be used for del'ing an attribute
 |    doc
 |      docstring
 |  
 |  Typical use is to define a managed attribute x:
 |  
 |  class C(object):
 |      def getx(self): return self._x
 |      def setx(self, value): self._x = value
 |      def delx(self): del self._x
 |      x = property(getx, setx, delx, "I'm the 'x' property.")
 |  
 |  Decorators make defining new properties or modifying existing ones easy:
 |  
 |  class C(object):
 |      @property
 |      def x(self):
 |          "I am the 'x' property."
 |          return self._x
 |      @x.setter
 |      def x(self, value):
 |          self._x = value
 |      @x.deleter
 |      def x(self):
 |          del s

#                                        Inheritance

In [11]:
##method resolution order
class Employee:
    raise_amt=1.04
    def __init__(self,first,last,pay):
        self.first=first
        self.last=last
        self.email=self.first+'.'+self.last+'@gmail.com'
        self.pay=pay
        
    def fullname(self):
        return '{} {}'.format(self.first,self.last)
    
    def apply_raise(self):
        self.pay = int(self.pay*self.raise_amt)
        
        
class Developer(Employee):
    """I want to change raise amount by 10percentage"""
    raise_amt=1.10    
    # I want to add Programming language also in __init__ method
    # First way but it is Tedious task and code would look like dirty
#     def __init__(self,first,last,pay,prolang):
#         self.first=first
#         self.last=last
#         self.email=self.first+'.'+self.last+'@gmail.com'
#         self.pay=pay
#         self.prolang=prolang
    
    #Second way ,,,it is a better then before and look good 
#     def __init__(self,first,last,pay,prolang): 
#         Employee.__init__(self,first,last,pay) # We Can also try this but this is not good Practice
    
    #Third method --- Best method 
    def __init__(self,first,last,pay,prolang):
        super().__init__(first,last,pay)
        self.prolang=prolang
        
        
class Manager(Employee):
    
    def __init__(self,first,last,pay,employees=None):
        super.__init__(first,last,pay)
        if employees is None:
            self.employees = []
        else:
            self.employees = employees
    
    def add_emp(self,emp):
        if emp not in self.employees:
            self.employees.append(emp)
            
    def remove_emp(self,emp):
        if emp in self.employees:
            self.employees.remove(emp)
            
    def print_emps(self):
        for emp in self.employees:
            print('-->',emp.fullname())
            
    
      
# help(Developer)    It shows all the information which it have. we can also see mro. 
e1= Developer('akash','verma',100000,'python')
e2= Developer('golu','verma',200000,'python')

mag1 = Manager('Sue','smith',90000,[e1])
print(mag1.email)
mag1.fullname



# print(e1.email)
# print(e2.email)

# print(e1.email)
# print(e1.prolang)


akash.verma@gmail.com
python


In [13]:
print("\U0001F917","\U0001F917","\U0001F637","\U0001F62A","\U0001F618","\U0001F600","\U0001F917")

🤗 🤗 😷 😪 😘 😀 🤗


#      Subprocess

In [3]:
import subprocess
p1=subprocess.run(['ls','-la'])
print(p1.args)

['ls', '-la']


#  Threading

In [ ]:
"""We use threading to speed up Program"""

In [1]:
import time

start = time.perf_counter()

def do_somethng():
    print('Sleeping for 1 second.......')
    time.sleep(1)
    print("Done Sleeping")
    
do_somethng()

finish = time.perf_counter()

print(f'Finised in {round(finish-start,2)} seconds')

Sleeping for 1 second.......
Done Sleeping
Finised in 1.0 seconds


In [2]:
import time

start = time.perf_counter()

def do_somethng():
    print('Sleeping for 1 second.......')
    time.sleep(1)
    print("Done Sleeping")
    
do_somethng()
do_somethng()

finish = time.perf_counter()

print(f'Finised in {round(finish-start,2)} seconds')

Sleeping for 1 second.......
Done Sleeping
Sleeping for 1 second.......
Done Sleeping
Finised in 2.0 seconds


In [3]:
import threading 

import time

start = time.perf_counter()

def do_somethng():
    print('Sleeping for 1 second.......')
    time.sleep(1)
    print("Done Sleeping")

    

t1=threading.Thread(target=do_somethng)
t2=threading.Thread(target=do_somethng)

t1.start()
t2.start()



finish = time.perf_counter()

print(f'Finised in {round(finish-start,2)} seconds')

Sleeping for 1 second.......
Sleeping for 1 second.......
Finised in 0.0 seconds


In [4]:
import threading 

import time

start = time.perf_counter()

def do_somethng():
    print('Sleeping for 1 second.......')
    time.sleep(1)
    print("Done Sleeping")

    

t1=threading.Thread(target=do_somethng)
t2=threading.Thread(target=do_somethng)

t1.start()
t2.start()

t1.join()
t2.join()

finish = time.perf_counter()

print(f'Finised in {round(finish-start,2)} seconds')

Sleeping for 1 second.......
Sleeping for 1 second.......
Done Sleeping
Done Sleeping
Finised in 1.0 seconds


In [7]:
import threading 

import time

start = time.perf_counter()
threads=[]

def do_somethng(seconds):
    print(f'Sleeping for {seconds} second.......')
    time.sleep(seconds)
    print("Done Sleeping")

    
for _ in range(10):
    t = threading.Thread(target=do_somethng,args=[1.5])
    t.start()
    threads.append(t)
    
    
for thread in threads:
    thread.join()


finish = time.perf_counter()

print(f'Finised in {round(finish-start,2)} seconds')

Sleeping for 1.5 second.......
Sleeping for 1.5 second.......
Sleeping for 1.5 second.......
Sleeping for 1.5 second.......
Sleeping for 1.5 second.......
Sleeping for 1.5 second.......
Sleeping for 1.5 second.......Sleeping for 1.5 second.......

Sleeping for 1.5 second.......
Sleeping for 1.5 second.......
Done SleepingDone Sleeping
Done Sleeping

Done SleepingDone SleepingDone Sleeping


Done Sleeping
Done SleepingDone Sleeping
Done Sleeping

Finised in 1.51 seconds


In [24]:
import concurrent.futures

import time

start = time.perf_counter()


def do_somethng(seconds):
    print(f'Sleeping for {seconds} second.......')
    time.sleep(seconds)
    return "Done Sleeping"

with concurrent.futures.ThreadPoolExecutor() as executor:
    f1 = executor.submit(do_somethng,1) 
    print(f1.result())
    
    
finish = time.perf_counter()

print(f'Finised in {round(finish-start,2)} seconds')

Sleeping for 1 second.......
Done Sleeping
Finised in 1.0 seconds


In [28]:
import concurrent.futures

import time

start = time.perf_counter()


def do_somethng(seconds):
    print(f'Sleeping for {seconds} second.......')
    time.sleep(seconds)
    return f'Done Sleeping....{seconds}'

with concurrent.futures.ThreadPoolExecutor() as executor:
    f1 = executor.submit(do_somethng,1) 
    f2 = executor.submit(do_somethng,1) 
    print(f1.result())
    print(f2.result())
    
    
finish = time.perf_counter()

print(f'Finised in {round(finish-start,2)} seconds')

Sleeping for 1 second.......
Sleeping for 1 second.......
Done Sleeping....1
Done Sleeping....1
Finised in 1.0 seconds


In [29]:
start = time.perf_counter()

with concurrent.futures.ThreadPoolExecutor() as executor:
    results = [executor.submit(do_somethng,1) for _ in range(10)] 

    for f in concurrent.futures.as_completed(results):
        print(f.result())
    
finish = time.perf_counter()

print(f'Finised in {round(finish-start,2)} seconds')

Sleeping for 1 second.......Sleeping for 1 second.......

Sleeping for 1 second.......
Sleeping for 1 second.......Sleeping for 1 second.......

Sleeping for 1 second.......
Sleeping for 1 second.......
Sleeping for 1 second.......Sleeping for 1 second.......
Sleeping for 1 second.......

Done Sleeping....1
Done Sleeping....1
Done Sleeping....1
Done Sleeping....1
Done Sleeping....1
Done Sleeping....1
Done Sleeping....1
Done Sleeping....1
Done Sleeping....1
Done Sleeping....1
Finised in 1.01 seconds


In [30]:
start = time.perf_counter()

with concurrent.futures.ThreadPoolExecutor() as executor:
    secs=[5,4,3,2,1]
    results = [executor.submit(do_somethng,sec) for sec in secs] 

    for f in concurrent.futures.as_completed(results):
        print(f.result())
    
finish = time.perf_counter()

print(f'Finised in {round(finish-start,2)} seconds')

Sleeping for 5 second.......
Sleeping for 4 second.......
Sleeping for 3 second.......
Sleeping for 2 second.......
Sleeping for 1 second.......
Done Sleeping....1
Done Sleeping....2
Done Sleeping....3
Done Sleeping....4
Done Sleeping....5
Finised in 5.01 seconds


In [31]:
start = time.perf_counter()

with concurrent.futures.ThreadPoolExecutor() as executor:
    secs=[5,4,3,2,1]
    results = executor.map(do_somethng,secs)
    
    for result in results:
        print(result)
finish = time.perf_counter()

print(f'Finised in {round(finish-start,2)} seconds')

Sleeping for 5 second.......
Sleeping for 4 second.......
Sleeping for 3 second.......
Sleeping for 2 second.......
Sleeping for 1 second.......
Done Sleeping....5
Done Sleeping....4
Done Sleeping....3
Done Sleeping....2
Done Sleeping....1
Finised in 5.01 seconds


In [40]:
import requests
import time


img_urls = [
    'https://images.unsplash.com/photo-1516117172878-fd2c41f4a759',
    'https://images.unsplash.com/photo-1532009324734-20a7a5813719',
    'https://images.unsplash.com/photo-1524429656589-6633a470097c',
    'https://images.unsplash.com/photo-1530224264768-7ff8c1789d79',
    'https://images.unsplash.com/photo-1564135624576-c5c88640f235',
    'https://images.unsplash.com/photo-1541698444083-023c97d3f4b6',
    'https://images.unsplash.com/photo-1522364723953-452d3431c267',
    'https://images.unsplash.com/photo-1513938709626-033611b8cc03',
    'https://images.unsplash.com/photo-1507143550189-fed454f93097',
    'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e',
    'https://images.unsplash.com/photo-1504198453319-5ce911bafcde',
    'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99',
    'https://images.unsplash.com/photo-1516972810927-80185027ca84',
    'https://images.unsplash.com/photo-1550439062-609e1531270e',
    'https://images.unsplash.com/photo-1549692520-acc6669e2f0c'
]

t1 = time.perf_counter()


for img_url in img_urls:
    img_bytes = requests.get(img_url).content
    img_name = img_url.split('/')[3]
    img_name = f'{img_name}.jpg'
    with open(img_name, 'wb') as img_file:
        img_file.write(img_bytes)
        print(f'{img_name} was downloaded...')




t2 = time.perf_counter()

print(f'Finished in {t2-t1} seconds')

photo-1516117172878-fd2c41f4a759.jpg was downloaded...
photo-1532009324734-20a7a5813719.jpg was downloaded...
photo-1524429656589-6633a470097c.jpg was downloaded...
photo-1530224264768-7ff8c1789d79.jpg was downloaded...
photo-1564135624576-c5c88640f235.jpg was downloaded...
photo-1541698444083-023c97d3f4b6.jpg was downloaded...
photo-1522364723953-452d3431c267.jpg was downloaded...
photo-1513938709626-033611b8cc03.jpg was downloaded...
photo-1507143550189-fed454f93097.jpg was downloaded...
photo-1493976040374-85c8e12f0c0e.jpg was downloaded...
photo-1504198453319-5ce911bafcde.jpg was downloaded...
photo-1530122037265-a5f1f91d3b99.jpg was downloaded...
photo-1516972810927-80185027ca84.jpg was downloaded...
photo-1550439062-609e1531270e.jpg was downloaded...
photo-1549692520-acc6669e2f0c.jpg was downloaded...
Finished in 29.12880120400041 seconds


In [41]:
import requests
import time
import concurrent.futures

img_urls = [
    'https://images.unsplash.com/photo-1516117172878-fd2c41f4a759',
    'https://images.unsplash.com/photo-1532009324734-20a7a5813719',
    'https://images.unsplash.com/photo-1524429656589-6633a470097c',
    'https://images.unsplash.com/photo-1530224264768-7ff8c1789d79',
    'https://images.unsplash.com/photo-1564135624576-c5c88640f235',
    'https://images.unsplash.com/photo-1541698444083-023c97d3f4b6',
    'https://images.unsplash.com/photo-1522364723953-452d3431c267',
    'https://images.unsplash.com/photo-1513938709626-033611b8cc03',
    'https://images.unsplash.com/photo-1507143550189-fed454f93097',
    'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e',
    'https://images.unsplash.com/photo-1504198453319-5ce911bafcde',
    'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99',
    'https://images.unsplash.com/photo-1516972810927-80185027ca84',
    'https://images.unsplash.com/photo-1550439062-609e1531270e',
    'https://images.unsplash.com/photo-1549692520-acc6669e2f0c'
]

t3 = time.perf_counter()


def download_image(img_url):
    img_bytes = requests.get(img_url).content
    img_name = img_url.split('/')[3]
    img_name = f'{img_name}.jpg'
    with open(img_name, 'wb') as img_file:
        img_file.write(img_bytes)
        print(f'{img_name} was downloaded...')

        
with concurrent.futures.ThreadPoolExecutor() as executor:
    executor.map(download_image, img_urls)


t4 = time.perf_counter()

print(f'Finished in {t4-t3} seconds')

photo-1516117172878-fd2c41f4a759.jpg was downloaded...
photo-1564135624576-c5c88640f235.jpg was downloaded...
photo-1549692520-acc6669e2f0c.jpg was downloaded...
photo-1507143550189-fed454f93097.jpg was downloaded...
photo-1516972810927-80185027ca84.jpg was downloaded...
photo-1504198453319-5ce911bafcde.jpg was downloaded...
photo-1530224264768-7ff8c1789d79.jpg was downloaded...
photo-1513938709626-033611b8cc03.jpg was downloaded...
photo-1550439062-609e1531270e.jpg was downloaded...
photo-1524429656589-6633a470097c.jpg was downloaded...
photo-1530122037265-a5f1f91d3b99.jpg was downloaded...
photo-1522364723953-452d3431c267.jpg was downloaded...
photo-1532009324734-20a7a5813719.jpg was downloaded...
photo-1541698444083-023c97d3f4b6.jpg was downloaded...
photo-1493976040374-85c8e12f0c0e.jpg was downloaded...
Finished in 26.5474217280007 seconds


# MultiPrpocessing

In [42]:
import time

start = time.perf_counter()

def do_somethng():
    print('Sleeping for 1 second.......')
    time.sleep(1)
    print("Done Sleeping")
    
do_somethng()

finish = time.perf_counter()

print(f'Finised in {round(finish-start,2)} seconds')

Sleeping for 1 second.......
Done Sleeping
Finised in 1.01 seconds


In [46]:
import multiprocessing 
start = time.perf_counter()

processes=[]
for _ in range(10):
    p=multiprocessing.Process(target=do_somethng)
    p.start()
    processes.append(p)
    
for process in processes:
    process.join()


finish = time.perf_counter()

print(f'Finised in {round(finish-start,2)} seconds')

Sleeping for 1 second.......
Sleeping for 1 second.......
Sleeping for 1 second.......
Sleeping for 1 second.......
Sleeping for 1 second.......
Sleeping for 1 second.......
Sleeping for 1 second.......
Sleeping for 1 second.......
Sleeping for 1 second.......
Sleeping for 1 second.......
Done Sleeping
Done Sleeping
Done Sleeping
Done Sleeping
Done Sleeping
Done Sleeping
Done Sleeping
Done Sleeping
Done Sleeping
Done Sleeping
Finised in 1.16 seconds


In [47]:
start = time.perf_counter()

def do_somethng(seconds):
    print(f'Sleeping for {seconds} second(s).......')
    time.sleep(seconds)
    print("Done Sleeping")

    
processes=[]
for _ in range(10):
    p=multiprocessing.Process(target=do_somethng,args=[1.5])
    p.start()
    processes.append(p)
    
    
for process in processes:
    process.join()


finish = time.perf_counter()

print(f'Finised in {round(finish-start,2)} seconds')

Sleeping for 1.5 second(s).......
Sleeping for 1.5 second(s).......
Sleeping for 1.5 second(s).......
Sleeping for 1.5 second(s).......
Sleeping for 1.5 second(s).......
Sleeping for 1.5 second(s).......
Sleeping for 1.5 second(s).......
Sleeping for 1.5 second(s).......
Sleeping for 1.5 second(s).......
Sleeping for 1.5 second(s).......
Done Sleeping
Done Sleeping
Done Sleeping
Done Sleeping
Done Sleeping
Done Sleeping
Done Sleeping
Done Sleeping
Done Sleeping
Done Sleeping
Finised in 1.66 seconds


In [52]:
import concurrent.futures
start = time.perf_counter()
def do_somethng(seconds):
    print(f'Sleeping for {seconds} second(s).......')
    time.sleep(seconds)
    return "Done Sleeping"

    
with concurrent.futures.ProcessPoolExecutor() as executor:
    f1=executor.submit(do_somethng,1)
    print(f1.result())

finish = time.perf_counter()

print(f'Finised in {round(finish-start,2)} seconds')

Sleeping for 1 second(s).......
Done Sleeping
Finised in 1.12 seconds


In [53]:
import concurrent.futures
start = time.perf_counter()
def do_somethng(seconds):
    print(f'Sleeping for {seconds} second(s).......')
    time.sleep(seconds)
    return "Done Sleeping"

    
with concurrent.futures.ProcessPoolExecutor() as executor:
    f1=executor.submit(do_somethng,1)
    f2=executor.submit(do_somethng,1)
    print(f1.result())
    print(f2.result())

finish = time.perf_counter()

print(f'Finised in {round(finish-start,2)} seconds')

Sleeping for 1 second(s).......
Sleeping for 1 second(s).......
Done Sleeping
Done Sleeping
Finised in 1.18 seconds


In [57]:
import concurrent.futures
start = time.perf_counter()
def do_somethng(seconds):
    print(f'Sleeping for {seconds} second(s).......')
    time.sleep(seconds)
    return f'Done Sleeping...{seconds}'

    
with concurrent.futures.ProcessPoolExecutor() as executor:
    secs=[5,4,3,2,1]
    results = [executor.submit(do_somethng,sec) for sec in secs]
    
    for f in concurrent.futures.as_completed(results):
        print(f.result())

finish = time.perf_counter()

print(f'Finised in {round(finish-start,2)} seconds')

Sleeping for 5 second(s).......
Sleeping for 4 second(s).......
Sleeping for 3 second(s).......
Sleeping for 2 second(s).......
Sleeping for 1 second(s).......
Done Sleeping...1
Done Sleeping...2
Done Sleeping...3
Done Sleeping...4
Done Sleeping...5
Finised in 5.14 seconds


# File handling 

# Exception Handling

                                    MetaClass and Design pattern

In [7]:
class Test(object):
    
    myvar=222     # Class variable
    
    def __init__(self,num=1):
        self.num=num       #instance variable and public
        self.__numa=122    #instance variable and Private
        
    def getter(self):
        return self.__numa
    
    def setter(self,value):
        self.__numa=value
    
    @property
    def methoda(self):
        print('I am method A')
    
    @staticmethod
    def methodb(): 
        print("I am static method")
#     @classmethod    
    def classvaraccess(cls):      #class method to access the class variable
        print("this is class variable{}".format(cls.myvar))
        
    def __str__(self):
        return "This is only recape purpose"
    
        
        
if __name__ == "__main__":
    obj=Test()
    print(obj.methoda)
    print(obj.methodb())
    print(Test.methodb())
    print(obj.classvaraccess())
    
    

    

I am method A
None
I am static method
None
I am static method
None
this is class variable222
None


In [8]:
"""There are 6 ways to define the class but here  i am only writting 3 method"""

#Method 1st for making a class
class A:
    def __init__(self):
        pass
    
    def __str__(self):
        return "This is demo class A"
    
#Method 2nd for making a class  
class B(object):
    def __call__(cls,*args,**kwargs):
        return super(B,cls).__call__(cls,*args,**kwargs)
    
    def __str__(self):
        return "This is demo class B"
    
# 3rd Method of making the class
class C(object):
    def __new__(cls,*args,**kwargs):
        print("creating the object")
        return super(C,cls).__new__(cls,*args,**kwargs)
    
    def __init__(self,*args,**kwargs):
        print("creating the instance")
        super(C,self).__init__(*args,**kwargs)
        
    def __str__(self):
        return "This is demo class C"
        
a=A()
print(a)
b=B()
print(b)
c=C()
print(c)

This is demo class A
This is demo class B
creating the object
creating the instance
This is demo class C


In [11]:
#Method 4
class D(type):
    def __call__(cls,*args,**kwargs):
        instance=super(D,cls).__call__(cls,*args,**kwargs)
        return instance
        
    def __init__(cls,name,base,attr):
        super(D,cls).__init__(name,base,attr)
        
class E(metaclass=D):
    pass
        
#Method 5

class F(type):
    def __call__(cls,*args,**kwargs):
        instance=super(D,cls).__call__(cls,*args,**kwargs)
        return instance
        
    def __init__(cls,name,base,attr):
        super(D,cls).__init__(name,base,attr)
        
class G(metaclass=F):
    def __new__(cls,*args,**kwargs):
        return super(C,cls).__new__(cls,*args,**kwargs)
    
    def __init__(self,*args,**kwargs):
        super(C,self).__init__(*args,**kwargs)
        
        
#Method 6    
class Meta(type):
    def __new__(cls,*args,**kwargs):
        return super(Meta,cls).__new__(cls,*args,**kwargs)
    
    def __init__(self,*args,**kwargs):
        super(Meta,self).__init__(*args,**kwargs)
        
class A1(metaclass=Meta):
    def __init__(self):
        pass
    
a1=A1()
print(a1)

In [23]:
#singleton desing pattern
class Metaclass(type):
    """ This is singleton desgin pattern """
    _instance={}
    
    def __call__(cls,*args,**kwargs):
        """if instance already exists then no need oto create"""
        if cls not in cls._instance:
            cls._instance[cls]=super(Metaclass,cls).__call__(*args,**kwargs)
            return cls._instance[cls]

    
class A(metaclass=Metaclass):
    def __init__(self):
        pass   
    
    
obj=A() 
print(obj)
obj1=A() 
print(obj1)

None


In [2]:
#Factory design pattern

class A(object):
    def __init__(self):
        pass
    
    def methodA(self):
        print("method A")
        
class B(object):
    def __init__(self):
        pass
    
    def methodB(self):
        print("method B")        
        
def get(obj=''):
    objs=dict(a=A(),b=B())
    return objs[obj]


a=get('a')
a.methodA()
b=get('b')
b.methodB()

method A
method B


In [6]:
## facade desing pattern
class Sensors(object):
    def __init__(self):
        pass
    
    def sensoron(self):
        print("sensor is on")
     
    def sensoroff(self):
        print("sensor is off")

class Lights(object):
    def __init__(self):
        pass
    
    def lighton(self):
        print("light is on")
     
    def lightoff(self):
        print("light is off")
        
class Smokes(object):
    def __init__(self):
        pass    
    
    def smokeon(self):
        print("smoke is on")
     
    def smokeoff(self):
        print("smoke is off")    
    
class Facade(object):
    def __init__(self):  
        self.__sensor=Sensors()
        self.__smoke=Smokes() 
        self.__light=Lights()
        
    def Emergency(self):
        self.__sensor.sensoron()
        self.__light.lighton()
        self.__smoke.smokeon()
        
    def normal(self):
        self.__sensor.sensoroff()
        self.__light.lightoff()
        self.__smoke.smokeoff()   
        
if __name__ == "__main__":
    obj=Facade()
    sensor=60
    
    if sensor>30:
        obj.Emergency()
    else:
        obj.normal()
        

sensor is on
light is on
smoke is on


In [9]:
#Facade + singleton + Metaclass
class Sensors(object):
    def __init__(self):
        pass
    
    def sensoron(self):
        print("sensor is on")
     
    def sensoroff(self):
        print("sensor is off")

class Lights(object):
    def __init__(self):
        pass
    
    def lighton(self):
        print("light is on")
     
    def lightoff(self):
        print("light is off")
        
class Smokes(object):
    def __init__(self):
        pass    
    
    def smokeon(self):
        print("smoke is on")
     
    def smokeoff(self):
        print("smoke is off")  
        
class Meta(type):
    """single design pattern"""
    _instance={}
    def __call__(cls,*args,**kwargs):
        """creating the object"""
        if cls not in cls._instance:
            cls._instance[cls]=super(Meta,cls).__call__(*args,**kwargs)
            return cls._instance[cls]
    
class Facade(metaclass=Meta):
    def __init__(self):  
        self.__sensor=Sensors()
        self.__smoke=Smokes() 
        self.__light=Lights()
        
    def Emergency(self):
        self.__sensor.sensoron()
        self.__light.lighton()
        self.__smoke.smokeon()
        
    def normal(self):
        self.__sensor.sensoroff()
        self.__light.lightoff()
        self.__smoke.smokeoff()   
        
if __name__ == "__main__":
    obj1=Facade()
    print(obj1)
    obj2=Facade()
    print(obj2)

None


In [14]:
#problem """ user could not add instance variable at run time """
class Test(object):
    def __init__(self):
        pass
    
if __name__== "__main__":
    obj1=Test()
    obj1.name="akash verma"
    obj1.rollnum='22'
#     print(obj1.__dict__)
    print(obj1.name)
    
"""we will use slots to slove this problem"""    

akash verma


'we will use slots to slove this problem'

In [24]:
#Solution of upper problem
class Test1(object):
    __slots__=("name") ###  instead of tuple, can be use []
    def __init__(self,name):
        self.name=name
          
    
if __name__== "__main__":
    obj2=Test1("akash")
    obj2.rollnum="001"
    print(obj2.name)

AttributeError: 'Test1' object has no attribute 'rollnum'

In [34]:
try:
    import os
    import datetime
    import sys
    import logging
except Exception as e:
    print("Some modules are missing please check all module {}".format(e))
    
class Meta(type):
    """Meta class"""
    
    def __call__(cls,*args,**kwargs):
        instance=super(Meta,cls).__call__(*args,**kwargs)
        return instance
    def __init__(cls,name,base,attr):
        super(Meta,cls).__init__(name,base,attr)
        
    
class log(object):    
    def __init__(self,func):
        self.func=func
        
    def __call__(self,*args,**kwargs):
        """wrapper function"""
        
        start= datetime.datetime.now()      #start time
        tem= self.func(self,*args,**kwargs)      #call the function
        funcname = self.func.__name__       #get the function
        end= datetime.datetime.now()        #end time
        
        
        message= """                    #From message
        
        funtion : {}
        Execution time : {}
        Address : {}
        Memmory : {}Bytes
        Date : {}
        """.format(funcname,
                   end-start,
                   self.func.__name__,
                   sys.getsizeof(self.func),
                   start)
        
        cwd = os.getcwd()
        print(cwd)
        folder = 'Logs'
        newpath = os.path.join(cwd,folder)
        
        try:
            """try to create a folder"""
            os.mkdir(newpath)
        except:
            """Directory already exists"""
            logging.basicConfig(filename='{}/log.log'.format(newpath),level=logging.DEBUG)
            logging.debug(message)
            return tem
        
class Test2(metaclass=Meta):
    def __init__(self,*args,**kwargs):
        pass
    @log
    def methodA(self):
        print("Hello")
        return "111"
    
if __name__ == "__main__":
    obj1=Test2()
    print(obj1.methodA())

Hello
/home/akash/Documents/all codes/Data structure
111


Objective: How can we Impose Rules while Creating classes with MetaClass
- Class should only be Created if First Letter is Capital Other wise throw error
- Class Should have a constructor other wise should throw Error
- All Method Should start with Lower case ie function name should start with Lower case
- Every Function should be provided with a Doc String other wise class should not be created
- There should be only one instance created of class Implementing Singleton Design Pattern
- Should not be able to add parameters at Run Time we use slots using Descriptors and Decorators

In [40]:
try:
    import functools
    import datetime
    import os
    import sys
    import logging
    from abc import  ABC, ABCMeta,abstractmethod
except Exception as e:
    print("Some Modules are Missing {}".format(e))


class MetaClass(type):

    """ Meta class """

    _instance = {}

    def __call__(cls, *args, **kwargs):

        """ Implementing Singleton Design Pattern  """

        print("**kwargs", kwargs)

        name = kwargs.get("name", None)
        if not name.__str__:
            raise ValueError ("name should be string ")

        if cls not in cls._instance:
            cls._instance[cls] = super(MetaClass, cls).__call__(*args, **kwargs)
            return cls._instance[cls]

    def __init__(cls, name, base, attr):

        """ Defining Your Own Rules  """

        if cls.__name__[0].isupper():

            """ Create class only if First Letter is Capital    """

            for k, v in attr.items():
                if hasattr(v, '__call__'):

                    if v.__name__[0] == '_' or v.__name__[0].islower():

                        """  check name function starts with _ or lower case  """

                        if v.__doc__ is None:

                            """  Check is User has provided Documentation """

                            raise ValueError("Make sure to Provide Documentation check {}".format(v.__name__))
                        else:

                            """ if function has Doccumentation pass """

                            pass
                    else:

                        """ function name starts with upper case throw error  """

                        raise ValueError("Function should start with Lower case :{}".format(v.__name__))
        else:
            raise ValueError("Class Name  should start with Capital Letter :{} ".format(cls.__name__[0]))

class log(object):

    """ Create a Log File regarding Execution Time memory Address size etc """

    def __init__(self, func):
        """ Constructor  """
        self.func = func

    def __call__(self, *args, **kwargs):
        """ Wrapper Function """

        start = datetime.datetime.now()     # start time
        Tem = self.func(*args, **kwargs)    # call Function
        FunName = self.func.__name__        # get Function Name
        end = datetime.datetime.now()       # End time

        message = """                       # Form Message
            
            Function : {}
            Execution Time : {}
            Address : {}
            Memory: {} Bytes
            Date: {}
            
            """.format(FunName,
                       end-start,
                       self.func.__name__,
                       sys.getsizeof(self.func),
                       start)

        cwd = os.getcwd()                       # get CWD
        folder = 'Logs1'                         # Create Folder Logs
        newPath = os.path.join(cwd, folder)     # change Path

        try:
            """ try to create directory """
            os.mkdir(newPath)                   # create Folder

        except Exception as e:

            """ Directory already exists """

            logging.basicConfig(filename='{}/log.log'.format(newPath), level=logging.DEBUG)
            logging.debug(message)

        return Tem


class Test(metaclass=MetaClass):

    __slots__ = ["name"]            # User wont be able to add elements at run time

    def __init__(self, name):

        """ Constructor """

        self.name = name
        super(Test, self).__init__()

    def method(self):

        """ Method """
        print("Hello World ")


if __name__ == "__main__":
    obj = Test(name="akash")
    print(obj)


**kwargs {'name': 'akash'}


In [60]:
class Foo(object):
    def __init__(self,name):
        self._name=name
        
    @property
    def name(self):
        return self._name
    
    @name.setter
    def name(self, value):
        self._name=value
        
if __name__ == "__main__":
    d1=Foo("akash")
    print(d1)

In [68]:
class Descriptor(object):
    
    def __init__(self,name=None):
        self.name=name
        
    def __get__(self,instance,owner):
        print("__get__")
        return instance
    
    def __set__(self,instance,value):
        print("__set__")
        instance.__dict__[self.name]=value
        
    def __delete__(self,instance):
        print("__del__")
        del instance.__dict__[self.name]
        
        
class Foo(Descriptor):
    name=Descriptor()
    
    
if __name__ == "__main__":
    obj=Foo(name="akash")
    print(obj)
    print(obj.name)
    obj.name="golu"
    print(obj.name)
#     Foo.__dict__

__set__
__get__
__set__
__get__


In [70]:
f = lambda : print("I am a function")   
print(f)
f()

<function <lambda> at 0x7fae51b98950>
I am a function


In [71]:
exec("""f()""")

I am a function


In [72]:
f.__call__()

I am a function


In [74]:
B= lambda : print("this is a function b")

l=[]
l.append(A)
l.append(B)
print(l)

for i in l:
    print(i.__call__())

[<class '__main__.A'>, <function <lambda> at 0x7fae51dfc950>]
this is a function b
None


In [80]:
class A(object):
    def __init__(self):
        pass
    
    def mathodA(self):
        print("Fun A")

        
class B(object):
    def __init__(self):
        pass
    
    def mathodB(self):
        print("Fun B")
        
class Stack(object):
    def __init__(self):
        self.data=[]
        
class Macro(object):
    def __init__(self):
        self.a=A()
        self.b=B()
        self.stack = Stack()
        
    def createMacro(self):
        self.stack.data.append(self.a.mathodA)
        self.stack.data.append(self.b.mathodB)
        
    def executeMacro(self):
        self.createMacro()
        
        for x in self.stack.data:
            print(x.__call__())
            
if __name__ == "__main__":
    obj=Macro()
    obj.executeMacro()
                    

Fun A
None
Fun B
None


In [125]:
from functools import wraps
from inspect import signature

class Contract(object):
    
    @classmethod
    def check(cls,value):
        pass 

class Typed(Contract):
    type = None
    
    @classmethod
    def check(cls,value):
        assert isinstance(value,cls.type),"Excpected type {}".format(cls.type)
        super().check(value)
        
class Integer(Typed):
    type = int
    
    
class String(Typed):
    type = str

class Float(Typed):
    type = float


class Positive(Contract):
    @classmethod
    def check(cls,value):
        assert value>0 ,"Value should be greater than zero"
        super().check(value)
        
class PositiveInteger(Integer,Positive):
    pass

   
class Negative(Contract):
    @classmethod
    def check(cls,value):
        assert value<0 ,"Value should be greater than zero"
        super().check(value)
        
class NegativeInteger(Integer,Negative):
    pass

class PosString(Contract):
    @classmethod
    def check(cls,value):
        assert len(value)>2,"Please Provide right String!"
        
        """I couldn't find this error way"""
#         if(len(value)>2):
#             print("as")
#             TypeError("String length should be greater than zero")
            
   
    
    
class PositiveString(String,PosString):
    pass
        
       
class Person(object):
    def __init__(self,name):
        self.name=PositiveString.check(name)
        
        
class checked(object):
    def __init__(self,func):
        self.func=func
        
    def __call__(self,*args,**kwargs):
        self.sig=signature(self.func)
        ann=self.func.__annotations__
        bound=self.sig.bind(*args,**kwargs)
        print("sig",self.sig)
        print("an",ann)
        print("bound",bound)
        
        for name,val in bound.arguments.items():
            if name in ann:
                ann[name].check(val)
                
        return self.func(*args,**kwargs)        
            
@checked
def fun12(a:PositiveInteger):
    print("Inside Function {}".format(a))
    
          
        
    
if __name__ == "__main__":
    a = fun12(123)
    print(a)
    
    
    
        

sig (a: __main__.PositiveInteger)
an {'a': <class '__main__.PositiveInteger'>}
bound <BoundArguments (a=123)>
Inside Function 123
None


In [129]:
class Base(object):
    _fields=[]
    def __init__(self,*args,**kwargs):
        for name, value in zip(self._fields, args):
            print(name,"=",value)
            setattr(self,name,value)
            

class Person(Base):
    _fields = ["name"]
    def method(self):
        print("Ok Name is {}".format(self.name))
    
if __name__ == "__main__":
    obj = Person("akash")
    print(obj)
    obj.method()

name = akash
Ok Name is akash


In [139]:
from inspect import Signature,Parameter

def make_signature(names):
    return Signature(
        Parameter(name,Parameter.POSITIONAL_OR_KEYWORD)
        for name in names    
        
    )


class Base(object):
    __signature__= make_signature([]) 
    def __init__(self,*args,**kwargs):
        bound = self.__signature__.bind(*args,**kwargs)
        print("Bound",bound)
        for name, value in bound.arguments.items():
            print(name,"=",value)
            setattr(self,name,value)
            

class Person(Base):
    __signature__=make_signature(["name"])
    def method(self):
        print("Ok Name is {}".format(self.name))
    
if __name__ == "__main__":
    obj = Person(name="akash")
    print(obj)
    obj.method()

Bound <BoundArguments (name='akash')>
name = akash
Ok Name is akash


                                        MetaProgramming

In [2]:
arrived_guests = ["John", "Ashley", "Danny", "Bobby"]

for guest in arrived_guests:
    arrived_order = arrived_guests.index(guest) + 1
    print(f"# {arrived_order}: {guest}")
    
print()
for guest_i in range(len(arrived_guests)):
    guest = arrived_guests[guest_i]
    print(f"# {guest_i + 1}: {guest}")

# 1: John
# 2: Ashley
# 3: Danny
# 4: Bobby

# 1: John
# 2: Ashley
# 3: Danny
# 4: Bobby


In [3]:
for guest_i, guest in enumerate(arrived_guests, 1):
    print(f"# {guest_i}: {guest}")

# 1: John
# 2: Ashley
# 3: Danny
# 4: Bobby


In [1]:
a = np.array([[1, 2, 3, 4, 5]])
print(a.shape)
weights = np.dot(a.T, a) / 15
print(weights.shape)
weights = np.repeat(weights[:, :, np.newaxis], 5, axis=-1)
print(weights.shape)
weights = np.repeat(weights[:, :, :, np.newaxis], 5, axis=-1)
print(weights.shape)
weights[:, :, 0, 1:] = 0
print(weights.shape)
weights[:, :, 1, 0] = 0
print(weights.shape)
weights[:, :, 1, 2] = 0
print(weights.shape)
weights[:, :, 2, :2] = 0
print(weights.shape)
weights = [weights, np.zeros(3)]
# print(weights)
qw = np.array(weights)
print(len(qw))

(1, 5)
(5, 5)
(5, 5, 5)
(5, 5, 5, 5)
(5, 5, 5, 5)
(5, 5, 5, 5)
(5, 5, 5, 5)
(5, 5, 5, 5)
2


/home/akash/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:19: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.


In [10]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import os,csv,sys
import pathlib
import glob
import cv2
from PIL import Image
import numpy as np


In [13]:
ls

 ada/                     GeeksForgeeks.ipynb
 algorithms.ipynb*       'new rough python code practice.ipynb'
 clear                   'Rough codes.ipynb'*
'DATA STRUCTURE.ipynb'*   Untitled.ipynb*


In [16]:
img1=cv2.imread('ada/img1.png')
img1=cv2.cvtColor(img1,cv2.COLOR_BGR2RGB)
img2=cv2.imread('ada/img2.png')
img1=cv2.cvtColor(img2,cv2.COLOR_BGR2RGB)
mask1=cv2.imread('ada/mask1.png')
mask1=cv2.cvtColor(mask1,cv2.COLOR_BGR2RGB)
mask2=cv2.imread('ada/mask2.png')
mask2=cv2.cvtColor(mask2,cv2.COLOR_BGR2RGB)
print(img1.shape,img2.shape,mask1.shape,mask2.shape)
print(type(img1))

(256, 256, 3) (256, 256, 3) (256, 256, 3) (256, 256, 3)
<class 'numpy.ndarray'>


In [23]:
p=[img1,img2]
q=[mask1,mask2]
w=(p,q)

In [25]:
r=np.array(w[0][0])
r.shape

(256, 256, 3)

In [20]:
print(len(p))

2


In [2]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [3]:
weights2 = np.dot(a.T,a)/25
weights2=weights2[:5,:5]
weights2.shape

(5, 5)

In [2]:
import numpy as np

In [45]:
a = np.array([[1,2,3,4,5,4,3,2,1]])
print(a[:,:5])
print(a.shape)

[[1 2 3 4 5]]
(1, 9)


In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape)

p = np.repeat(arr, 3, 0)
print(p)
print(p.shape)

q = np.repeat(arr, 3, -1)
print(q)
print(q.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]
(6, 3)
[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]
(2, 9)


In [5]:
weights = np.dot(a.T, a) / 25
print(weights)
print(weights.shape)

[[0.04 0.08 0.12 0.16 0.2  0.16 0.12 0.08 0.04]
 [0.08 0.16 0.24 0.32 0.4  0.32 0.24 0.16 0.08]
 [0.12 0.24 0.36 0.48 0.6  0.48 0.36 0.24 0.12]
 [0.16 0.32 0.48 0.64 0.8  0.64 0.48 0.32 0.16]
 [0.2  0.4  0.6  0.8  1.   0.8  0.6  0.4  0.2 ]
 [0.16 0.32 0.48 0.64 0.8  0.64 0.48 0.32 0.16]
 [0.12 0.24 0.36 0.48 0.6  0.48 0.36 0.24 0.12]
 [0.08 0.16 0.24 0.32 0.4  0.32 0.24 0.16 0.08]
 [0.04 0.08 0.12 0.16 0.2  0.16 0.12 0.08 0.04]]
(9, 9)


In [17]:
we2 = weights[:, :, np.newaxis]
print(we2)
print(we2.shape)

[[[0.04]
  [0.08]
  [0.12]
  [0.16]
  [0.2 ]
  [0.16]
  [0.12]
  [0.08]
  [0.04]]

 [[0.08]
  [0.16]
  [0.24]
  [0.32]
  [0.4 ]
  [0.32]
  [0.24]
  [0.16]
  [0.08]]

 [[0.12]
  [0.24]
  [0.36]
  [0.48]
  [0.6 ]
  [0.48]
  [0.36]
  [0.24]
  [0.12]]

 [[0.16]
  [0.32]
  [0.48]
  [0.64]
  [0.8 ]
  [0.64]
  [0.48]
  [0.32]
  [0.16]]

 [[0.2 ]
  [0.4 ]
  [0.6 ]
  [0.8 ]
  [1.  ]
  [0.8 ]
  [0.6 ]
  [0.4 ]
  [0.2 ]]

 [[0.16]
  [0.32]
  [0.48]
  [0.64]
  [0.8 ]
  [0.64]
  [0.48]
  [0.32]
  [0.16]]

 [[0.12]
  [0.24]
  [0.36]
  [0.48]
  [0.6 ]
  [0.48]
  [0.36]
  [0.24]
  [0.12]]

 [[0.08]
  [0.16]
  [0.24]
  [0.32]
  [0.4 ]
  [0.32]
  [0.24]
  [0.16]
  [0.08]]

 [[0.04]
  [0.08]
  [0.12]
  [0.16]
  [0.2 ]
  [0.16]
  [0.12]
  [0.08]
  [0.04]]]
(9, 9, 1)


In [10]:
weights = np.repeat(weights[:, :, np.newaxis], 3, axis=-1)
print(weights)
print(weights.shape)

[[[0.04 0.04 0.04]
  [0.08 0.08 0.08]
  [0.12 0.12 0.12]
  [0.16 0.16 0.16]
  [0.2  0.2  0.2 ]
  [0.16 0.16 0.16]
  [0.12 0.12 0.12]
  [0.08 0.08 0.08]
  [0.04 0.04 0.04]]

 [[0.08 0.08 0.08]
  [0.16 0.16 0.16]
  [0.24 0.24 0.24]
  [0.32 0.32 0.32]
  [0.4  0.4  0.4 ]
  [0.32 0.32 0.32]
  [0.24 0.24 0.24]
  [0.16 0.16 0.16]
  [0.08 0.08 0.08]]

 [[0.12 0.12 0.12]
  [0.24 0.24 0.24]
  [0.36 0.36 0.36]
  [0.48 0.48 0.48]
  [0.6  0.6  0.6 ]
  [0.48 0.48 0.48]
  [0.36 0.36 0.36]
  [0.24 0.24 0.24]
  [0.12 0.12 0.12]]

 [[0.16 0.16 0.16]
  [0.32 0.32 0.32]
  [0.48 0.48 0.48]
  [0.64 0.64 0.64]
  [0.8  0.8  0.8 ]
  [0.64 0.64 0.64]
  [0.48 0.48 0.48]
  [0.32 0.32 0.32]
  [0.16 0.16 0.16]]

 [[0.2  0.2  0.2 ]
  [0.4  0.4  0.4 ]
  [0.6  0.6  0.6 ]
  [0.8  0.8  0.8 ]
  [1.   1.   1.  ]
  [0.8  0.8  0.8 ]
  [0.6  0.6  0.6 ]
  [0.4  0.4  0.4 ]
  [0.2  0.2  0.2 ]]

 [[0.16 0.16 0.16]
  [0.32 0.32 0.32]
  [0.48 0.48 0.48]
  [0.64 0.64 0.64]
  [0.8  0.8  0.8 ]
  [0.64 0.64 0.64]
  [0.48 0.48 0.48]
  

In [11]:
weights = np.repeat(weights[:,:,np.newaxis],3,axis=-1)
print(weights)
print(weights.shape)

[[[[0.04 0.04 0.04 0.04 0.04 0.04 0.04 0.04 0.04]]

  [[0.08 0.08 0.08 0.08 0.08 0.08 0.08 0.08 0.08]]

  [[0.12 0.12 0.12 0.12 0.12 0.12 0.12 0.12 0.12]]

  [[0.16 0.16 0.16 0.16 0.16 0.16 0.16 0.16 0.16]]

  [[0.2  0.2  0.2  0.2  0.2  0.2  0.2  0.2  0.2 ]]

  [[0.16 0.16 0.16 0.16 0.16 0.16 0.16 0.16 0.16]]

  [[0.12 0.12 0.12 0.12 0.12 0.12 0.12 0.12 0.12]]

  [[0.08 0.08 0.08 0.08 0.08 0.08 0.08 0.08 0.08]]

  [[0.04 0.04 0.04 0.04 0.04 0.04 0.04 0.04 0.04]]]


 [[[0.08 0.08 0.08 0.08 0.08 0.08 0.08 0.08 0.08]]

  [[0.16 0.16 0.16 0.16 0.16 0.16 0.16 0.16 0.16]]

  [[0.24 0.24 0.24 0.24 0.24 0.24 0.24 0.24 0.24]]

  [[0.32 0.32 0.32 0.32 0.32 0.32 0.32 0.32 0.32]]

  [[0.4  0.4  0.4  0.4  0.4  0.4  0.4  0.4  0.4 ]]

  [[0.32 0.32 0.32 0.32 0.32 0.32 0.32 0.32 0.32]]

  [[0.24 0.24 0.24 0.24 0.24 0.24 0.24 0.24 0.24]]

  [[0.16 0.16 0.16 0.16 0.16 0.16 0.16 0.16 0.16]]

  [[0.08 0.08 0.08 0.08 0.08 0.08 0.08 0.08 0.08]]]


 [[[0.12 0.12 0.12 0.12 0.12 0.12 0.12 0.12 0.12]]

  [[0.24

[[[[0.04 0.   0.   0.   0.   0.   0.   0.   0.  ]]

  [[0.08 0.   0.   0.   0.   0.   0.   0.   0.  ]]

  [[0.12 0.   0.   0.   0.   0.   0.   0.   0.  ]]

  [[0.16 0.   0.   0.   0.   0.   0.   0.   0.  ]]

  [[0.2  0.   0.   0.   0.   0.   0.   0.   0.  ]]

  [[0.16 0.   0.   0.   0.   0.   0.   0.   0.  ]]

  [[0.12 0.   0.   0.   0.   0.   0.   0.   0.  ]]

  [[0.08 0.   0.   0.   0.   0.   0.   0.   0.  ]]

  [[0.04 0.   0.   0.   0.   0.   0.   0.   0.  ]]]


 [[[0.08 0.   0.   0.   0.   0.   0.   0.   0.  ]]

  [[0.16 0.   0.   0.   0.   0.   0.   0.   0.  ]]

  [[0.24 0.   0.   0.   0.   0.   0.   0.   0.  ]]

  [[0.32 0.   0.   0.   0.   0.   0.   0.   0.  ]]

  [[0.4  0.   0.   0.   0.   0.   0.   0.   0.  ]]

  [[0.32 0.   0.   0.   0.   0.   0.   0.   0.  ]]

  [[0.24 0.   0.   0.   0.   0.   0.   0.   0.  ]]

  [[0.16 0.   0.   0.   0.   0.   0.   0.   0.  ]]

  [[0.08 0.   0.   0.   0.   0.   0.   0.   0.  ]]]


 [[[0.12 0.   0.   0.   0.   0.   0.   0.   0.  ]]

  [[0.24

In [26]:
weights[:,:,0,1:]=0
weights[:,:,1,0]=0
weights[:,:,1,2]=0
weights[:,:,2,:2]=0

IndexError: too many indices for array

In [7]:
b=np.array([[[1,2,3,4,5,6]]])
print(b.shape)

(1, 1, 6)


In [14]:
c=np.array([[[1,2,3,4,5,6]],[[1,2,3,4,5,6]],[[1,2,3,4,5,6]]])
print(c)

[[[1 2 3 4 5 6]]

 [[1 2 3 4 5 6]]

 [[1 2 3 4 5 6]]]


In [ ]:
#checkpoint_path = model_name
checkpoint_path = None
checkpoint_path_10x='/content/drive/MyDrive/new_4x_model/model.h5'  

if checkpoint_path is not None:
    # Load m for continue training
    model = load_model(checkpoint_path, custom_objects={'fscore': fscore,'jaccard_distance_loss':jaccard_distance_loss})
    model.load_weights("%s/weights.160.hdf5"%weights_folder) # To continue from a particular epoch
    initial_epoch = 100


else:
    print("akash")

    model_10x = load_model(checkpoint_path_10x, custom_objects={'fscore': fscore})
    model_10x.load_weights("%s/weights.160.hdf5"%weights_folder_10x)


    initial_epoch = 0

    a = np.array([[1,2,3,4,5,4,3,2,1]])
    weights = np.dot(a.T,a)/25
    weights = np.repeat(weights[:,:,np.newaxis],3,axis=-1)
    weights = np.repeat(weights[:,:,:,np.newaxis],3,axis=-1)
    weights[:,:,0,1:]=0
    weights[:,:,1,0]=0
    weights[:,:,1,2]=0
    weights[:,:,2,:2]=0
    weights = [weights, np.zeros(3)]

    weights2 = np.dot(a[:,:5].T,a[:,:5])/25
    weights2 = np.repeat(weights2[:,:,np.newaxis],5,axis=-1)
    weights2 = np.repeat(weights2[:,:,:,np.newaxis],5,axis=-1)
    weights2[:,:,0,1:]=0
    weights2[:,:,1,0] =0
    weights2[:,:,1,2:]=0
    weights2[:,:,2,:2]=0
    weights2[:,:,2,3:]=0
    weights2[:,:,3,:3]=0
    weights2[:,:,3,4:]=0
    weights2[:,:,4,:4]=0
    weights2 = [weights2, np.zeros(5)]  


    b = np.hamming(5)
    b = b[np.newaxis,:]
    c = np.dot(b.T,b)/5
    hamming_flr = np.repeat(c[:,:,np.newaxis],3,axis=-1)
    hamming_flr = hamming_flr[:,:,:,np.newaxis]
    hamming_flr= [hamming_flr, np.zeros(3)]
    #hamming_flr= [hamming_flr, np.zeros(1)]
    
    
    size = 256
    
    X_input = Input(shape=(size,size,3))
    
    #print(K.int_shape(X_input))


    X = Conv2DTranspose(3, kernel_size=(9,9), strides=(5, 5), padding='same',output_padding= None, activation=None)(X_input)
    #X = UpSampling2D(size=(5, 5), data_format=None, interpolation='bilinear')(X_input)
    ### size of layer =(size*stride)

    print('up',K.int_shape(X))
    X = DepthwiseConv2D(kernel_size=(5,5),strides=(2,2), padding='same')(X)
    #X = AveragePooling2D((2,2))(X)
    print('down',K.int_shape(X))

    X = model_10x(X)

    def resize(x):
            #X = K.resize_images(x,0.4,0.4,data_format='channels_last',interpolation='bilinear')
            X = resize_bilinear(x,(size,size))
            return X
    # X = Lambda(resize)(X)

    X=Conv2DTranspose(5, kernel_size=(5,5), strides=(2, 2), padding='same',output_padding= None, activation=None)(X)
    #print('upsamp',K.int_shape(X))
    print('resize',K.int_shape(X))
    X = DepthwiseConv2D(kernel_size=(7,7),strides=(5,5), padding='same')(X)
    print('down',K.int_shape(X))
    #print('downsamp',K.int_shape(X))




    b2 = np.hamming(7)
    b2 = b2[np.newaxis,:]
    c2 = np.dot(b2.T,b2)/7
    hamming_flr2 = np.repeat(c2[:,:,np.newaxis],5,axis=-1)
    hamming_flr2 = hamming_flr2[:,:,:,np.newaxis]
    hamming_flr2= [hamming_flr2, np.zeros(5)]


    model_4x_to_10x = Model(inputs = X_input, outputs = X, name='Model_4x')

    lay1 = model_4x_to_10x.layers[1].get_weights()
    lay2 = model_4x_to_10x.layers[2].get_weights()
    lay4 = model_4x_to_10x.layers[4].get_weights()
    # print(lay4)
    lay5 = model_4x_to_10x.layers[5].get_weights()



    model_4x_to_10x.layers[1].set_weights(weights)
    model_4x_to_10x.layers[2].set_weights(hamming_flr)
    model_4x_to_10x.layers[4].set_weights(weights2)
    model_4x_to_10x.layers[5].set_weights(hamming_flr2)

    # Start/resume training

    final_epoch = initial_epoch + 1
    # model_4x_to_10x.layers[3].trainable = False
    # model.load_weights('weights_4x/weights.002.hdf5')

In [1]:
import mysql.connector

In [3]:
mydb=mysql.connector.connect(host="localhost",user='root',password='')

In [4]:
print(mydb.connection_id)

11


In [1]:
def func():
  nums = [[2], [4], [6], [8]]
  return sum(nums, [])
  
print(func())

[2, 4, 6, 8]


In [2]:
def my_func(i, j):
  x = i | j
  return x


i = 7
j = 8

if __name__ == "__main__": 
  x = my_func(i, j)
  print(x)

15


In [3]:
a = 1
b = 1
k = a+b
k = k + True
print(k)

3


In [7]:
x = 'abcd'
for i in range(len(x)):
    x[i].upper() 
print(x)

abcd


In [8]:
tuple1=(25)
print(tuple1)
print(type(tuple1))

25
<class 'int'>


In [9]:
t = [9, 41, 19, 22, 74, 15]
t[2:4]

[19, 22]

In [13]:
if True or True:
    if False and True or False:
        print('A')
    elif False and False or True and True:
         print('B') 
    else:
         print('C') 
else:
     print('D')

B


In [16]:
x=12
def f1(a,b=x):
      print(a,b)
x=15
f1(4)

4 12


In [17]:
from random import random
def fun(x=random()):
     print(x)

fun()
fun()

0.6676779161565146
0.6676779161565146


In [18]:
print(0.7+0.2==0.9)

False


In [19]:
num1 = 0
def out_func():
    
    num1 = 1
    def in_func():
        nonlocal num1
        num1 = 2

    in_func()
    return num1

num2 = out_func()
print(num1, num2)

0 2


In [20]:
def my_func(st):
    l1 = [ch for ch in st if ch.isalpha()]
    return ''.join(l1.pop() if ch.isalpha() else ch for ch in st)


st = 'ab-cd-ef'
print(my_func(st))

fe-dc-ba


In [21]:
def my_func(num):
    data = [0]
    for i in range(1, num+1):
        data.append(data[i >> 1] + int(i & 1))
    return data


num = 6
print(my_func(num))

[0, 1, 1, 2, 1, 2, 2]
